import { Inter } from 'next/font/google';
import './globals.css';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Script src="//imasdk.googleapis.com/js/sdkloader/ima3.js"></Script>
      <body className={(inter.className, 'text-neutral-600')}>{children}</body>
    </html>
  );
}
